reasons = [
    "Kein Sitzplatz",
    "Kaputtes WC",
    "Heizung im Sommer/Klima im Winter",
    '"Bitte die Türen freigeben"',
    "Halt entfällt",
    "Zug fällt aus",
    "Oberleitungsstörung",
    '"Netter" Bahnbegleiter',
    "Wagen mit reservierten Plätzen wurde abgekoppelt",
    "Recklinghausen Süd",
    "Streik",
    "Schienenersatz-Verkehr",
    "Überholung durch einen anderen Zug",
    "Zugstau",
    "Bettler im Zug",
    'Durchsage: "Trickbetrüger im Zug/Bahnhof"',
    "Trompeter am Morgen",
    "Fußballspiel",
    '"Verzögert sich […] auf unbestimmte Zeit"',
    "Personen im Gleis",
    "Notarzteinsatz am Gleis",
    "Kaputter Wagon (der leer ist aber mit fährt)",
    "Anzeigetafel: Bitte Durchsagen beachten",
    "Umgekehrte Wagenreihung",
    "Raucher im Nichtraucherbereich",
    "Anschluss verpasst",
    "Schulklasse",
]
